mj:
  accounts:
    - guild-id: "${MJ_ACCOUNT_1_GUILD_ID}"       
      channel-id: "${MJ_ACCOUNT_1_CHANNEL_ID}"   
      user-token: "${MJ_ACCOUNT_1_USER_TOKEN}"   
      user-agent: "${MJ_ACCOUNT_1_USER_AGENT}"  
      enable: true
      core-size: 3
      queue-size: 10
      timeout-minutes: 5
  task-store:
    type: in_memory  
    timeout: 30d    
  translate-way: null            
